// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ciftlik2.Models;

#nullable disable

namespace ciftlik2.Migrations
{
    [DbContext(typeof(CiftlikDbContext))]
    [Migration("20251213125859_SifirdanKurulums")]
    partial class SifirdanKurulums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ciftlik2.Models.AsiKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsiIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AsiTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.ToTable("AsiKayitlari");
                });

            modelBuilder.Entity("ciftlik2.Models.Hayvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<decimal?>("AlisFiyati")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("AlisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnaKupeNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaKupeNumarasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CikisNedeni")
                        .HasColumnType("int");

                    b.Property<string>("Cins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeldigiYer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirisSekli")
                        .HasColumnType("int");

                    b.Property<bool>("Kisirlastirildi")
                        .HasColumnType("bit");

                    b.Property<string>("KupeNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LaktasyonSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KupeNumarasi")
                        .IsUnique();

                    b.ToTable("Hayvanlar");
                });

            modelBuilder.Entity("ciftlik2.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("ciftlik2.Models.SutKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<int>("SagilanHayvanSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vakit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SutKayitlari");
                });

            modelBuilder.Entity("ciftlik2.Models.TedaviKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DenetleyenVeteriner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.Property<string>("KullanilanIlac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceteyiYazanVeteriner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SutArinmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Teshis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.ToTable("TedaviKayitlari");
                });

            modelBuilder.Entity("ciftlik2.Models.TestKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HayvanId")
                        .HasColumnType("int");

                    b.Property<string>("Sonuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TestTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HayvanId");

                    b.ToTable("TestKayitlari");
                });

            modelBuilder.Entity("ciftlik2.Models.Tohumlanma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisiHayvanId")
                        .HasColumnType("int");

                    b.Property<int?>("ErkekHayvanId")
                        .HasColumnType("int");

                    b.Property<int>("GebelikTestDurumu")
                        .HasColumnType("int");

                    b.Property<int?>("GebelikTestiSonucu")
                        .HasColumnType("int");

                    b.Property<DateTime>("TohumlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TohumlanmaTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisiHayvanId");

                    b.HasIndex("ErkekHayvanId");

                    b.ToTable("Tohumlanmalar");
                });

            modelBuilder.Entity("ciftlik2.Models.YemAlisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double>("Miktar")
                        .HasColumnType("float");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("YemTuru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("YemAlimlari");
                });

            modelBuilder.Entity("ciftlik2.Models.AsiKaydi", b =>
                {
                    b.HasOne("ciftlik2.Models.Hayvan", "Hayvan")
                        .WithMany("AsiKayitlari")
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("ciftlik2.Models.TedaviKaydi", b =>
                {
                    b.HasOne("ciftlik2.Models.Hayvan", "Hayvan")
                        .WithMany("TedaviKayitlari")
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("ciftlik2.Models.TestKaydi", b =>
                {
                    b.HasOne("ciftlik2.Models.Hayvan", "Hayvan")
                        .WithMany("TestKayitlari")
                        .HasForeignKey("HayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hayvan");
                });

            modelBuilder.Entity("ciftlik2.Models.Tohumlanma", b =>
                {
                    b.HasOne("ciftlik2.Models.Hayvan", "DisiHayvan")
                        .WithMany("Tohumlanmalar")
                        .HasForeignKey("DisiHayvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ciftlik2.Models.Hayvan", "ErkekHayvan")
                        .WithMany()
                        .HasForeignKey("ErkekHayvanId");

                    b.Navigation("DisiHayvan");

                    b.Navigation("ErkekHayvan");
                });

            modelBuilder.Entity("ciftlik2.Models.Hayvan", b =>
                {
                    b.Navigation("AsiKayitlari");

                    b.Navigation("TedaviKayitlari");

                    b.Navigation("TestKayitlari");

                    b.Navigation("Tohumlanmalar");
                });
#pragma warning restore 612, 618
        }
    }
}
